name: caching
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: control execution flow
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: prepare cache content
              run: |
                mkdir cachedir
                cd cachedir
                echo "hello there" >> file.txt
            - name: cache data
              uses: actions/cache@v4
              with:
                path: cachedir
                key: cachefile
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
            - name: cache data
             uses: actions/cache@v4
              with:
                path: cachedir
                key: cachefile
            - name: check data
              run: |
                ls -lrt
                cd cachedir
                ls -lrt
            