name: caching
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: control execution flow
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: list file
              run: ls -lrt
            - name: install dependencies
              id: install-packages
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            - name: cache dependancies
              if: failure() && steps.install-packages.outcome == 'failure'
              run:
                echo "running after failure from previous step"
    deploy1:
        runs-on: ubuntu-latest
        steps:
            - name: show values
              run: echo "hollaaa"

    # Run this job only if any of the job fails defined in needs
    show-failure-job:
        if: failure()
        runs-on: ubuntu-latest
        needs: 
            - build
            - deploy1
        steps:
            - name: Output information
              run: |
                echo "something went wrong"

                if [ "${{ needs.build.result }}" == "failure" ]
                then
                    echo "build job has failed"
                fi

                if [ "${{ needs.deploy1.result }}" == "failure" ]
                then
                    echo "deploy job has failed"
                fi